server:
  port: 8080
spring:
  application:
    name: h-video
  datasource:
    url: jdbc:mysql://${h-video.db.host}:3306/h_video?useSSL=false&serverTimezone=UTC
    username: root
    password: *****
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${h-video.redis.host}
    port: 6379
    password: *****
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  main:
    allow-circular-references: true # 允许循环依赖
logging:
  level:
    com.harvey.hvideo: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  type-aliases-package: com.harvey.hvideo.pojo.entity
knife4j:
  enable: true
  openapi:
    title: h-video
    description: "视频系统接口文档,被拦截的用户(未登录的),将没有返回值, 而是statue_code = 401"
    email: harvey.blocks@outlook.com
    concat: Harvey Blocks
    url: https://www.baidu.com
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.harvey.hvideo.controller
# jwt配置
h-video:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: ***** # 解析文件的密钥(文件本身也是密钥)
    tokenTTL: 2400h
  auth:
    include-paths:
      - "/user/logout"
      - "/user/me"
      - "/user/update"
      - "/user/create"
      - "/upload/video/**"
    root-auth-paths:
      - "/user/create"
  constants:
    authorization-header: "authorization"
    redis-host: ${h-video.redis.host}
    es-host: ${h-video.es.host}
    video-upload-dir: ${h-video.file-save-path.video}
    image-upload-dir: ${h-video.file-save-path.img}
    restrict-request-times: "20"
    clear-click-history-wait-seconds: 600
    max-page-size: 10
    default-page-size: 5
